/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2a111125-61de-46b6-9693-bb3e0315ae97",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ztdWQM2Di",
    "aws_user_pools_web_client_id": "21m0mi347u670qhm048tqo4ba4",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tjfxdlh4kncu3ijhfmtyx4h6ii.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-p7tq4a3w6rfq5n2w5rarixftxu"
};


export default awsmobile;
